# -*- coding: utf-8 -*-
"""linear regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12qvZVzi2i9xZA59HIbJ6ildxO7BGEMgd
"""

import pandas as pd

import numpy as np

df = pd.read_csv('/content/Salary_Data.csv')

df.head()

df.tail()

df.info()

df.describe().T

import seaborn as sns

sns.distplot(df['Salary'])

sns.distplot(df['YearsExperience'])

from sklearn.model_selection import train_test_split

x = df.iloc[:,:-1]
y = df.iloc[:,-1]

# Correct the order of variable assignments in train_test_split:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
# Now, x_train and y_train will have consistent sample sizes.

#x_test.shape

from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(x_train,y_train)

y_pred = lr.predict(x_test)

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

mse = mean_squared_error(y_test,y_pred)
mae = mean_absolute_error(y_test,y_pred)
r2 = r2_score(y_test,y_pred)

r2

import pickle

with open('lr_model.pkl','wb') as z:
  pickle.dump(lr,z)

